-- DuckPipe Snowflake Role Setup
-- Run this as ACCOUNTADMIN or SECURITYADMIN in your Snowflake account.
-- Replace <WAREHOUSE> and <DATABASE> with your actual names.

-- ═══════════════════════════════════════════════════════
-- Tier 1: Read-Only (Sandbox)
-- ═══════════════════════════════════════════════════════

CREATE ROLE IF NOT EXISTS DUCKPIPE_READER;

GRANT USAGE ON WAREHOUSE <WAREHOUSE> TO ROLE DUCKPIPE_READER;
GRANT USAGE ON DATABASE <DATABASE> TO ROLE DUCKPIPE_READER;
GRANT USAGE ON ALL SCHEMAS IN DATABASE <DATABASE> TO ROLE DUCKPIPE_READER;
GRANT SELECT ON ALL TABLES IN DATABASE <DATABASE> TO ROLE DUCKPIPE_READER;
GRANT SELECT ON ALL VIEWS IN DATABASE <DATABASE> TO ROLE DUCKPIPE_READER;

-- Future grants so new objects are automatically accessible:
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE <DATABASE> TO ROLE DUCKPIPE_READER;
GRANT SELECT ON FUTURE TABLES IN DATABASE <DATABASE> TO ROLE DUCKPIPE_READER;
GRANT SELECT ON FUTURE VIEWS IN DATABASE <DATABASE> TO ROLE DUCKPIPE_READER;

-- Query history access (reads ACCOUNT_USAGE, not your data):
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE DUCKPIPE_READER;

-- Create the service user:
CREATE USER IF NOT EXISTS DUCKPIPE_SVC
  PASSWORD = 'CHANGE_ME'
  DEFAULT_ROLE = DUCKPIPE_READER
  DEFAULT_WAREHOUSE = <WAREHOUSE>
  MUST_CHANGE_PASSWORD = FALSE;

GRANT ROLE DUCKPIPE_READER TO USER DUCKPIPE_SVC;


-- ═══════════════════════════════════════════════════════
-- Tier 2: Operator (supervised writes)
-- Only run this section when you're ready for Tier 2.
-- ═══════════════════════════════════════════════════════

CREATE ROLE IF NOT EXISTS DUCKPIPE_OPERATOR;
GRANT ROLE DUCKPIPE_READER TO ROLE DUCKPIPE_OPERATOR;

-- Allows: ALTER WAREHOUSE SUSPEND/RESUME, SYSTEM$CANCEL_QUERY()
-- Does NOT allow: CREATE, DROP, ALTER TABLE, INSERT, UPDATE, DELETE
GRANT OPERATE ON WAREHOUSE <WAREHOUSE> TO ROLE DUCKPIPE_OPERATOR;

-- To activate Tier 2, change the user's default role:
-- ALTER USER DUCKPIPE_SVC SET DEFAULT_ROLE = DUCKPIPE_OPERATOR;
-- GRANT ROLE DUCKPIPE_OPERATOR TO USER DUCKPIPE_SVC;
